"use client";

import { useState } from "react";
import { ArrowRight, Bot, Check, CheckCircle2, HelpCircle, LoaderCircle, Plus, Sparkles, X } from "lucide-react";

type Design={status:"needs-clarification"|"ready";name:string;summary:string;questions:Array<{id:string;question:string;why:string;options:string[];required:boolean}>;frontend:string[];backend:string[];data:string[];azure:string[];testing:string[];security:string[];acceptanceCriteria:string[]};

export function CustomCapabilityDesigner({authorizedFetch,repository,onAdd}:{authorizedFetch:(input:RequestInfo|URL,init?:RequestInit)=>Promise<Response>;repository:string;onAdd:(capability:{name:string;description:string;design:Design})=>void}){
 const[open,setOpen]=useState(false);const[description,setDescription]=useState("");const[design,setDesign]=useState<Design|null>(null);const[answers,setAnswers]=useState<Record<string,string>>({});const[loading,setLoading]=useState(false);const[error,setError]=useState("");
 async function generate(){setLoading(true);setError("");try{const response=await authorizedFetch("/api/capabilities/design",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({description,answers,repository})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Capability design failed.");setDesign(data);}catch(caught){setError(caught instanceof Error?caught.message:"Capability design failed.");}finally{setLoading(false)}}
 function add(){if(!design||design.status!=="ready")return;onAdd({name:design.name,description,design});setOpen(false);setDescription("");setDesign(null);setAnswers({});}
 if(!open)return <button className="add-capability-button" onClick={()=>setOpen(true)}><Plus size={16}/><span><strong>Design your own AI capability</strong><small>Describe the outcome. AI will ask clarifying questions and create an end-to-end implementation plan.</small></span><ArrowRight size={15}/></button>;
 return <section className="custom-capability"><div className="custom-capability-head"><div><div className="step-icon"><Sparkles size={18}/></div><div><strong>Custom AI capability designer</strong><span>Interactive requirements and implementation planning</span></div></div><button onClick={()=>setOpen(false)} aria-label="Close custom capability designer"><X size={16}/></button></div><label>Describe the capability and desired user outcome<textarea value={description} onChange={event=>setDescription(event.target.value)} placeholder="Example: Let service agents upload a customer contract, extract obligations, compare them with policy, and review cited recommendations before saving the result."/></label>{!design&&<button className="design-capability-action" disabled={loading||description.trim().length<20} onClick={()=>void generate()}>{loading?<><LoaderCircle className="spin" size={15}/>Designing capability…</>:<><Bot size={15}/>Analyze requirements</>}</button>}
 {design?.status==="needs-clarification"&&<div className="clarification-panel"><div className="clarification-title"><HelpCircle size={17}/><div><strong>Clarification required</strong><p>The AI needs these answers before it can design the frontend, backend, data, security, and test plan.</p></div></div>{design.questions.map(question=><label key={question.id}>{question.question}<small>{question.why}</small>{question.options.length?<select value={answers[question.id]||""} onChange={event=>setAnswers({...answers,[question.id]:event.target.value})}><option value="">Select an answer</option>{question.options.map(option=><option key={option}>{option}</option>)}</select>:<input value={answers[question.id]||""} onChange={event=>setAnswers({...answers,[question.id]:event.target.value})} placeholder="Enter your answer"/>}</label>)}<button className="design-capability-action" disabled={loading||design.questions.some(question=>question.required&&!answers[question.id]?.trim())} onClick={()=>void generate()}>{loading?<><LoaderCircle className="spin" size={15}/>Refining design…</>:<><Sparkles size={15}/>Generate implementation design</>}</button></div>}
 {design?.status==="ready"&&<div className="custom-design-result"><div className="custom-result-title"><CheckCircle2 size={18}/><div><strong>{design.name}</strong><p>{design.summary}</p></div></div><div className="custom-design-grid"><DesignArea title="Frontend experience" items={design.frontend}/><DesignArea title="Backend orchestration" items={design.backend}/><DesignArea title="Data lifecycle" items={design.data}/><DesignArea title="Azure services" items={design.azure}/><DesignArea title="Testing Agent plan" items={design.testing}/><DesignArea title="Security controls" items={design.security}/></div><details><summary>Acceptance criteria ({design.acceptanceCriteria.length})</summary>{design.acceptanceCriteria.map(item=><span key={item}><Check size={12}/>{item}</span>)}</details><button className="design-capability-action" onClick={add}><Plus size={15}/>Add capability to modernization</button></div>}{error&&<div className="error-note">{error}</div>}</section>;
}
function DesignArea({title,items}:{title:string;items:string[]}){return <div><strong>{title}</strong>{items.length?items.map(item=><span key={item}>{item}</span>):<span>Defined after clarification</span>}</div>}
