import { NextResponse } from "next/server";
import { z } from "zod";
import { AuthError, requireUser } from "@/lib/auth";
import { isDemoRequest } from "@/lib/demo-session";
import { env } from "@/lib/env";
import { foundryModelParameters } from "@/lib/foundry-model";
import { resilientFetch } from "@/lib/resilient-fetch";
import { enforceRateLimit } from "@/lib/rate-limit";

const requestSchema=z.object({description:z.string().trim().min(20).max(4000),answers:z.record(z.string(),z.string().max(2000)).default({}),repository:z.string().max(300).optional()});
const designSchema=z.object({status:z.enum(["needs-clarification","ready"]),name:z.string().min(2).max(100),summary:z.string().min(10).max(800),questions:z.array(z.object({id:z.string().min(1).max(80),question:z.string().min(5).max(500),why:z.string().max(500),options:z.array(z.string().max(200)).max(8).default([]),required:z.boolean().default(true)})).max(6),frontend:z.array(z.string().max(500)).max(8),backend:z.array(z.string().max(500)).max(8),data:z.array(z.string().max(500)).max(8),azure:z.array(z.string().max(500)).max(8),testing:z.array(z.string().max(500)).max(8),security:z.array(z.string().max(500)).max(8),acceptanceCriteria:z.array(z.string().max(500)).max(10)});

export async function POST(request:Request){try{const demo=isDemoRequest(request);if(!demo){const user=await requireUser(request,["Modernization.Reader","Modernization.Admin"]);const rate=await enforceRateLimit(user.tenantId,"capability.design",30,3600);if(!rate.allowed)return NextResponse.json({error:"The hourly capability-design limit has been reached."},{status:429,headers:{"Retry-After":String(rate.retryAfterSeconds)}});}const input=requestSchema.parse(await request.json());if(demo)return NextResponse.json(demoDesign(input));if(!env.AZURE_AI_FOUNDRY_ENDPOINT||!env.AZURE_AI_FOUNDRY_API_KEY)return NextResponse.json(deterministicDesign(input));
 const system=`You are a senior AI product architect. Turn a user's desired AI feature into an end-to-end implementation design for an existing application. If essential information is missing, return status needs-clarification and ask at most 4 concise questions. Otherwise return status ready. Return strict JSON with name, summary, questions [{id,question,why,options,required}], frontend, backend, data, azure, testing, security, acceptanceCriteria arrays. Every ready design must include visible frontend behavior, backend orchestration, authorization, data lifecycle, observability, tests, failure states, and measurable acceptance criteria. Never return markdown.`;
 const response=await resilientFetch(`${env.AZURE_AI_FOUNDRY_ENDPOINT.replace(/\/$/,"")}/chat/completions?api-version=${encodeURIComponent(process.env.AZURE_AI_FOUNDRY_API_VERSION||"2024-05-01-preview")}`,{method:"POST",headers:{"Content-Type":"application/json","api-key":env.AZURE_AI_FOUNDRY_API_KEY},body:JSON.stringify({model:env.AZURE_AI_FOUNDRY_MODEL,...foundryModelParameters(env.AZURE_AI_FOUNDRY_MODEL,.05),response_format:{type:"json_object"},messages:[{role:"system",content:system},{role:"user",content:JSON.stringify(input)}]}),attempts:3,timeoutMs:90000,operation:"foundry.capability_design"});
 if(!response.ok)return NextResponse.json(deterministicDesign(input));const payload=await response.json() as {choices?:Array<{message?:{content?:string}}>};const content=payload.choices?.[0]?.message?.content;if(!content)return NextResponse.json(deterministicDesign(input));try{return NextResponse.json(normalizeDesign(JSON.parse(extractJson(content)),input))}catch{return NextResponse.json(deterministicDesign(input))}
 }catch(error){if(error instanceof AuthError)return NextResponse.json({error:error.message},{status:error.status});if(error instanceof z.ZodError)return NextResponse.json({error:"Describe the capability in at least 20 characters.",issues:error.issues},{status:400});console.error("Capability design failed",error);return NextResponse.json({error:"Capability design could not be completed."},{status:500})}}

function normalizeDesign(raw:unknown,input:z.infer<typeof requestSchema>){const candidate=raw&&typeof raw==="object"?raw as Record<string,unknown>:{};const array=(key:string)=>(Array.isArray(candidate[key])?candidate[key]:[]).map(String).filter(Boolean).slice(0,8);const questions=Array.isArray(candidate.questions)?candidate.questions.slice(0,6).map((value,index)=>{const q=value&&typeof value==="object"?value as Record<string,unknown>:{};return{id:String(q.id||`question-${index+1}`),question:String(q.question||"Please provide more detail."),why:String(q.why||"This affects the implementation design."),options:Array.isArray(q.options)?q.options.map(String).slice(0,8):[],required:q.required!==false}}):[];return designSchema.parse({status:candidate.status==="needs-clarification"&&questions.length?"needs-clarification":"ready",name:String(candidate.name||"Custom AI capability"),summary:String(candidate.summary||input.description).slice(0,800),questions,frontend:array("frontend"),backend:array("backend"),data:array("data"),azure:array("azure"),testing:array("testing"),security:array("security"),acceptanceCriteria:array("acceptanceCriteria")})}
function deterministicDesign(input:z.infer<typeof requestSchema>){const answered=Object.keys(input.answers).length>0;if(!answered)return designSchema.parse({status:"needs-clarification",name:"Custom AI capability",summary:input.description,questions:[{id:"primary-users",question:"Who will use this capability and in which application workflow?",why:"This determines the frontend surface, permissions, and interaction design.",options:["Internal employees","Customers","Operations team","Administrators"],required:true},{id:"data-sources",question:"Which approved data sources should the capability use?",why:"Grounding, privacy, and retrieval architecture depend on the source systems.",options:["Application database","Uploaded documents","Enterprise search","External APIs"],required:true},{id:"success",question:"What measurable outcome defines success?",why:"The Testing Agent needs objective acceptance criteria.",options:[],required:true}],frontend:[],backend:[],data:[],azure:[],testing:[],security:[],acceptanceCriteria:[]});return readyDesign(input)}
function demoDesign(input:z.infer<typeof requestSchema>){return deterministicDesign(input)}
function readyDesign(input:z.infer<typeof requestSchema>){return designSchema.parse({status:"ready",name:"Custom AI capability",summary:input.description,questions:[],frontend:["Add a discoverable workflow entry point and responsive interaction panel.","Show loading, confidence, citations, validation, empty, and failure states.","Add user feedback and accessible keyboard interactions."],backend:["Create an authenticated orchestration API and asynchronous processing workflow.","Apply authorization and tenant-level access trimming before model calls.","Persist auditable requests, results, feedback, and operational state."],data:["Define approved source schemas, retention, provenance, and deletion behavior."],azure:["Use Microsoft Foundry inference, Application Insights, and managed identity.","Add Azure AI Search or Blob Storage only when required by selected sources."],testing:["Add unit, contract, integration, accessibility, adversarial, and end-to-end tests.","Validate groundedness, latency, failure recovery, and behavior parity."],security:["Protect prompts and tools against injection and unauthorized data access.","Redact secrets and personal data from model context and telemetry."],acceptanceCriteria:["Authorized users can complete the workflow from the application frontend.","Every response exposes source provenance or an explicit uncertainty state.","Failures are recoverable and observable without changing existing behavior."],...{}})}
function extractJson(content:string){const fenced=content.match(/```(?:json)?\s*([\s\S]*?)```/i)?.[1];const candidate=fenced||content;const start=candidate.indexOf("{");const end=candidate.lastIndexOf("}");return start>=0&&end>start?candidate.slice(start,end+1):candidate}
